name: Python package

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Print Environment Variables
        run: env
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run linters
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest -s -o log_cli=true --log-cli-level=WARNING